//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_Poliza
    {
        public long Id_ClientePoliza { get; set; }
        public long Id_Cliente { get; set; }
        public long Id_Poliza { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Poliza Poliza { get; set; }
    }
}
