//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poliza()
        {
            this.Cliente_Poliza = new HashSet<Cliente_Poliza>();
        }
    
        public long Id_Poliza { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public int Cobertura { get; set; }
        public System.DateTime Inicio_Vigencia { get; set; }
        public int Periodo_cobertura { get; set; }
        public decimal Precio { get; set; }
        public string Tipo_Riesgo { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente_Poliza> Cliente_Poliza { get; set; }
    }
}
